# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  left_elbow_pitch:
    has_velocity_limits: true
    max_velocity: 3.8700000000000001
    has_acceleration_limits: true
    max_acceleration: 1000.0
  left_elbow_yaw:
    has_velocity_limits: true
    max_velocity: 3.8700000000000001
    has_acceleration_limits: true
    max_acceleration: 1000.0
  left_shoulder_pitch:
    has_velocity_limits: true
    max_velocity: 3.5600000000000001
    has_acceleration_limits: true
    max_acceleration: 1000.0
  left_shoulder_roll:
    has_velocity_limits: true
    max_velocity: 3.5600000000000001
    has_acceleration_limits: true
    max_acceleration: 1000.0
  left_wrist_pitch:
    has_velocity_limits: true
    max_velocity: 4.71
    has_acceleration_limits: true
    max_acceleration: 1000.0
  left_wrist_roll:
    has_velocity_limits: true
    max_velocity: 4.71
    has_acceleration_limits: true
    max_acceleration: 1000.0
  left_wrist_yaw:
    has_velocity_limits: true
    max_velocity: 4.1799999999999997
    has_acceleration_limits: true
    max_acceleration: 1000.0
  right_elbow_pitch:
    has_velocity_limits: true
    max_velocity: 3.8700000000000001
    has_acceleration_limits: true
    max_acceleration: 1000.0
  right_elbow_yaw:
    has_velocity_limits: true
    max_velocity: 3.8700000000000001
    has_acceleration_limits: true
    max_acceleration: 1000.0
  right_shoulder_pitch:
    has_velocity_limits: true
    max_velocity: 3.5600000000000001
    has_acceleration_limits: true
    max_acceleration: 1000.0
  right_shoulder_roll:
    has_velocity_limits: true
    max_velocity: 3.5600000000000001
    has_acceleration_limits: true
    max_acceleration: 1000.0
  right_wrist_pitch:
    has_velocity_limits: true
    max_velocity: 4.71
    has_acceleration_limits: true
    max_acceleration: 1000.0
  right_wrist_roll:
    has_velocity_limits: true
    max_velocity: 4.71
    has_acceleration_limits: true
    max_acceleration: 1000.0
  right_wrist_yaw:
    has_velocity_limits: true
    max_velocity: 4.1799999999999997
    has_acceleration_limits: true
    max_acceleration: 1000.0