# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - left_arm_controller
    - right_arm_controller

  left_arm_controller:
    type: FollowJointTrajectory
    joints:
      - left_shoulder_pitch
      - left_shoulder_roll
      - left_elbow_yaw
      - left_elbow_pitch
      - left_wrist_yaw
      - left_wrist_pitch
      - left_wrist_roll
    action_ns: follow_joint_trajectory
    default: true
  right_arm_controller:
    type: FollowJointTrajectory
    joints:
      - right_shoulder_pitch
      - right_shoulder_roll
      - right_elbow_yaw
      - right_elbow_pitch
      - right_wrist_yaw
      - right_wrist_pitch
      - right_wrist_roll
    action_ns: follow_joint_trajectory
    default: true